<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <xs:element name="ott_subscription">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="subscription" maxOccurs="unbounded" minOccurs="1">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="user_id" type="xs:positiveInteger"/>
                            <xs:element name="user_name" type="xs:string"/>
                            <xs:element name="package" type="packageType"/>
                            <xs:element name="status" type="statusType"/>
                            <xs:element name="start_date" type="xs:date"/>
                            <xs:element name="end_date" type="xs:date"/>
                            <xs:element name="region" type="regionType"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:simpleType name="packageType">
        <xs:restriction base="xs:string">
            <xs:enumeration value="Premium"/>
            <xs:enumeration value="Standard"/>
            <xs:enumeration value="Basic"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="statusType">
        <xs:restriction base="xs:string">
            <xs:enumeration value="Active"/>
            <xs:enumeration value="Inactive"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="regionType">
        <xs:restriction base="xs:string">
            <xs:enumeration value="North America"/>
            <xs:enumeration value="Europe"/>
            <xs:enumeration value="Asia-Pacific"/>
            <xs:enumeration value="India"/>
        </xs:restriction>
    </xs:simpleType>

</xs:schema>
